package com.cg.paymentwallet.exception;

public interface IPaymentWalletException {

	String MESSAGE1 ="PHONE NUMBER NOT AVAILABLE";
	String MESSAGE2 = "PLEASE ENTER CORRECT PASSWORD";
	String MESSAGE3 = "PLEASE ENTER VALID PHONE NUMBER";
	String MESSAGE4 ="ENTER VALID MONEY";
	String MESSAGE5 = "ENTER CORRECT NUMBER";
	String MESSAGE6 = "ENTER VALID NAME";
	String MESSAGE7 = "ENTER VALID EMAIL";
	String MESSAGE8 = "ENTER VALID AGE";
	String MESSAGE9 = "ENTER VALID GENDER";
	String MESSAGE10 = "ENTERED WRONG LOGIN-ID OR PASSWORD PLEASE ENTER CORRECTLY";

}
